//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace TopGear_MVC_L2_Paging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [Required]
        public int Rollno { get; set; }

        [Required]
        [Display(Name = "Student name")]
        public string Sname { get; set; }

        [Required]
        [Display(Name = "Standards")]
        public string Std { get; set; }
    }
}
